- hosts: springapp
  remote_user: infra
  become: yes
  gather_facts: False

- name: apply frontend roles
  hosts: frontend
  remote_user: infra
  become: yes
  gather_facts: False
  roles:
    - role: ansible-nginx-role
      tags: nginx-role

- name: apply backend roles
  hosts: backend
  remote_user: infra
  become: yes
  gather_facts: False
  roles:
